[tool.poetry]
name = "disaster-routing-simulator"
version = "0.1.0"
description = ""
authors = [
    "Amalie Bøgild <malleboegild@gmail.com>",
    "Joachim Borup <joachim@borup.com>",
    "Mai Odgaard <odgaardmai@gmail.com>",
]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
osmnx = "^2.0.1"
matplotlib = "^3.10.0"
scikit-learn = "^1.6.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
